name: CICD

on:
  push:
    branches:
      - main
  
  workflow_dispatch: # manual trigger 


# Keep one CICD run active at a time so publish/test/promote happen in order
concurrency:
  group: ${{ github.workflow }}
  queue: max

jobs:
  cicd:
    if: github.repository == '<org>/<upstream repo>' # do not run on forks
    uses: canonical/inference-snaps-dev/.github/workflows/reuse-cicd.yaml@v2
    with:
      build-runner: |
        [ "ubuntu-24.04", "ubuntu-24.04-arm" ]
      store-track: latest
      snap-name: <snap-name> # get this from snap/snapcraft.yaml / name
      smoke-test-engine: cpu # get this from snap/snapcraft.yaml / env.FALLBACK_ENGINE
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN_MAIN }}
